### ISSUE TITLE
Add enzyme and enzyme-to-json testing packages to the frontend

### ISSUE THREAD

**Issue by Denijar** [SE701Group2/daily-focus#46]
**Developer Story**
As a developer, I want to be able to shallow render components so that I can create snapshot tests.

**Acceptance Criteria**
* enzyme package is added to the package.json
* enzyme-to-json package is added to the package.json

**Additional Context** 
enzyme package link: https://www.npmjs.com/package/enzyme
enzyme-to-json package link: https://www.npmjs.com/package/enzyme-to-json

how to write snapshot tests with jest (already added to the project) and enzyme: https://medium.com/opendoor-labs/testing-react-components-with-jest-a7e8e4d312d8

**Comment by dikunong** [comment]
It looks like Enzyme requires an adapter package specific to the version of React that we're using. Unfortunately, our project is using version `17.0.1` and there hasn't yet been an adapter released for React 17.

This is pretty well documented [in this GitHub issue in the original enzyme repo](https://github.com/enzymejs/enzyme/issues/2429). There appear to be a couple of unofficial alternatives, but both appear to have some issues - which would explain why the original has yet to be updated almost half a year after React 17 came out.

Possible solutions to this roadblock are to attempt to downgrade the project to React 16 (no feature differential between 16 and 17 so should work, but might be very messy to coordinate across everyone's forks), or to explore another frontend testing option (such as [React Testing Library](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme)). I've never done frontend testing before so I'm not sure what the best solution is at this stage. We should discuss this at tomorrow's meeting.

**Comment by dikunong** [comment]
It was decided during the [2021-03-18 full team meeting](https://github.com/SE701Group2/daily-focus/wiki/2021-03-18-Full-Team-Meeting) to downgrade React to version 16 to enable the usage of Enzyme. It's anticipated that this will cause no breakages due to no new features being added in v17, but we will have to keep an eye out for any potential regression issues.

**Comment by dikunong** [comment]
There have been continual issues getting this to work - after downgrading the project to React v16 and installing `enzyme`, the client now fails to build due to a missing npm dependency.

```
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"win32","arch":"x64"})
```

This appears to be the result of a dependency of a dependency (`enzyme` -> `chokidar` -> `fsevents`) being compatible with macOS only. It's unclear if this should be an optional dependency, but `npm install --no-optional` failed to remedy the issue.

For now, this appears to be unworthwhile to pursue further, when other options likely exist and are viable in the short amount of time before the demo & deadline. @kcho9906 will look into `react-test-renderer` as an alternative option.

**Comment by kcho9906** [comment]
Upon further investigation, the rollback of React to version 16 seems to work with npm version 6. The issues experienced by @dikunong earlier was potentially due to his machine running npm version 7. The team has decided to continue with the rollback and document this issue in the documentation of the project.

**Comment by dikunong** [comment]
Confirmed that it works on my machine after downgrading to npm v6. Thanks @kcho9906 and @Denijar for taking the investigation deep and figuring it out :)
